### ISSUE TITLE
Flexbox layout not supported?

### ISSUE THREAD

**Issue by mostwired** [NeXTs/Multiple.js#2]
If I use the multiple.js library together with flexbox items arranged in a wrappable row, gradient positioning is off in all the items.

**Comment by NeXTs** [comment]
hey

could you please provide some demo at codepen?

**Comment by NeXTs** [comment]
[Main demo](https://multiple.js.org/) uses flexbox and works fine.
Closing for now. Will reopen when someone provide example that reproduces this issue

![image](https://user-images.githubusercontent.com/1753208/28373168-56c93546-6caa-11e7-94f9-f2575772dcbc.png)
